### ISSUE TITLE
install fails

### ISSUE THREAD

**Issue by willyfromtheblock** [MatthewLM/valid-hash-server#1]
>  sudo python3 setup.py install
> Traceback (most recent call last):
>   File "setup.py", line 3, in <module>
>     from ez_setup import use_setuptools
>   File "/home/node/valid-hash-server/ez_setup.py", line 27, in <module>
>     from distutils import log
> ImportError: cannot import name 'log'

python3 --version
Python 3.6.6

**Comment by willyfromtheblock** [comment]
sudo apt-get install python3-distutils pip3

and

pip3 install setuptools 

fixed this.
